### ISSUE TITLE
Archive old repo

### ISSUE THREAD

**Issue by lgmorand** [Azure/the-aks-checklist#10]
migration should be full to this repository

```[tasklist]
### Tasks
- [x] Add a message on old repo and archive it
- [ ] Add connectionstring here to deploy from here
- [ ] archive the old repo
```

**Comment by lgmorand** [comment]
The old repo will only be archived when I'm 100% sure that the new repo is maintained as it's a one-time decision
